// Generated by tools/levels.ts from levels/. Do not edit: change levels/, then run
// `deno task levels`.
import type { Level } from "./types.ts";

export const tutorial: readonly Level[] = [{
  id: 1,
  code:
    "int f(int x, int y) {\n  // numbers represent colors\n  int red = 2;\n  return x == 1 && y == 2 ? red : 0;\n}",
  solution: [
    "00000000",
    "00000000",
    "02000000",
    "00000000",
    "00000000",
    "00000000",
    "00000000",
    "00000000",
  ],
}, {
  id: 2,
  code: "int f(int x, int y) {\n  // tip: drag to paint\n  return x;\n}",
  solution: [
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
  ],
}, {
  id: 3,
  code: "int f(int x, int y) {\n  // integer division\n  return x / 2;\n}",
  solution: [
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
  ],
}, {
  id: 4,
  code: "int f(int x, int y) {\n  return (x/2 + y/4) % 2;\n}",
  solution: [
    "00110011",
    "00110011",
    "00110011",
    "00110011",
    "11001100",
    "11001100",
    "11001100",
    "11001100",
  ],
}, {
  id: 5,
  code: "int f(int x, int y) {\n  // available: max, min, abs\n  return max(x, y);\n}",
  solution: [
    "01234567",
    "11234567",
    "22234567",
    "33334567",
    "44444567",
    "55555567",
    "66666667",
    "77777777",
  ],
}, {
  id: 6,
  code: "int f(int x, int y) {\n  // a comparison gives 1 or 0\n  return (x*2 < y) * 7;\n}",
  solution: [
    "00000000",
    "70000000",
    "70000000",
    "77000000",
    "77000000",
    "77700000",
    "77700000",
    "77770000",
  ],
}, {
  id: 7,
  code: "int f(int x, int y) {\n  int w[] = {1,2,3,4,4,3,2,1};\n  return x < w[y] ? 5 : 0;\n}",
  solution: [
    "50000000",
    "55000000",
    "55500000",
    "55550000",
    "55550000",
    "55500000",
    "55000000",
    "50000000",
  ],
}, {
  id: 8,
  code:
    "int f(int x, int y) {\n  // bitwise left shift\n  int b = 1 << x;\n  // hexadecimal bitmask\n  int mask = 0xB0; // 10110000\n  return b & mask ? 1 : 0;\n}",
  solution: [
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
  ],
}];

export const daily: readonly Level[] = [{
  id: 1,
  code:
    "int f(int x, int y) {\n  // 2*x - 7: 0 is the grid's center\n  int dx = 2*x - 7, dy = 2*y - 7;\n  return dx*dx + dy*dy < 6*6 ? 2:0;\n}",
  solution: [
    "00000000",
    "00222200",
    "02222220",
    "02222220",
    "02222220",
    "02222220",
    "00222200",
    "00000000",
  ],
}, {
  id: 2,
  code:
    "int f(int x, int y) {\n  int c = 0x80 >> x, r = 0x1 << y;\n  int m = 0x28;\n  return (c & m) | (r & m) ? 3 : 0;\n}",
  solution: [
    "00303000",
    "00303000",
    "00303000",
    "33333333",
    "00303000",
    "33333333",
    "00303000",
    "00303000",
  ],
}, {
  id: 3,
  code: "int f(int x, int y) {\n  return y ? f(y, x % y) : x;\n}",
  solution: [
    "01234567",
    "11111111",
    "21212121",
    "31131131",
    "41214121",
    "51111511",
    "61232161",
    "71111117",
  ],
}, {
  id: 4,
  code: "int f(int x, int y) {\n  return (x & y) == 0;\n}",
  solution: [
    "11111111",
    "10101010",
    "11001100",
    "10001000",
    "11110000",
    "10100000",
    "11000000",
    "10000000",
  ],
}, {
  id: 5,
  code:
    "int f(int x, int y) {\n  // one compare instead of two\n  unsigned u = x - 2, v = y - 3;\n  return u < 2 || v < 2 ? 1 : 2;\n}",
  solution: [
    "22112222",
    "22112222",
    "22112222",
    "11111111",
    "11111111",
    "22112222",
    "22112222",
    "22112222",
  ],
}, {
  id: 6,
  code:
    "int f(int x, int y) {\n  int dx = 2*x - 7, dy = 2*y - 7;\n  int d = dx*dx + dy*dy;\n  int z = 7;\n  while (z > 0 && d + z*z > 64)\n    z--;\n  return z;\n}",
  solution: [
    "00233200",
    "03566530",
    "25677652",
    "36777763",
    "36777763",
    "25677652",
    "03566530",
    "00233200",
  ],
}, {
  id: 7,
  code:
    "int f(int x, int y) {\n  int cat[] = {\n    0x81, 0xC3, 0xFF, 0xBD,\n    0xFF, 0xE7, 0x7E, 0x3C,\n  };\n  int fur = cat[y] << x & 0x80;\n  return fur ? 3 : y == 3 ? 5 : 0;\n}",
  solution: [
    "30000003",
    "33000033",
    "33333333",
    "35333353",
    "33333333",
    "33300333",
    "03333330",
    "00333300",
  ],
}, {
  id: 8,
  code: "int f(int x, int y) {\n  int d = abs(x - 3) + abs(y - 4);\n  return 5 - min(d, 5);\n}",
  solution: [
    "00010000",
    "00121000",
    "01232100",
    "12343210",
    "23454321",
    "12343210",
    "01232100",
    "00121000",
  ],
}, {
  id: 9,
  code:
    "int f(int x, int y) {\n  int a[] = {\n    0,0,0,0,0,0,0,0,\n    0,0,0,0,3,0,0,0,\n    0,0,0,0,3,3,0,0,\n    6,6,6,6,3,3,3,0,\n    6,6,6,6,3,3,3,0,\n    0,0,0,0,3,3,0,0,\n    0,0,0,0,3,0,0,0,\n    0,0,0,0,0,0,0,0};\n  return a[y + x*8];\n}",
  solution: [
    "00066000",
    "00066000",
    "00066000",
    "00066000",
    "03333330",
    "00333300",
    "00033000",
    "00000000",
  ],
}, {
  id: 10,
  code: "int f(int x, int y) {\n  return x ^ y;\n}",
  solution: [
    "01234567",
    "10325476",
    "23016745",
    "32107654",
    "45670123",
    "54761032",
    "67452301",
    "76543210",
  ],
}, {
  id: 11,
  code:
    "int f(int x, int y) {\n  int dx = abs(2*x - 7);\n  int dy = abs(2*y - 7);\n  return max(dx, dy) / 2;\n}",
  solution: [
    "33333333",
    "32222223",
    "32111123",
    "32100123",
    "32100123",
    "32111123",
    "32222223",
    "33333333",
  ],
}, {
  id: 12,
  code:
    "int f(int x, int y) {\n  int z = (x + y) & 0xA8;\n  int w = y*y*y + x*x*x;\n  int u = z ^ w;\n  int v = (u << 3) & 7;\n  return v | y;\n}",
  solution: [
    "00000000",
    "11111111",
    "22222222",
    "33333333",
    "44444444",
    "55555555",
    "66666666",
    "77777777",
  ],
}];
