// Generated by tools/levels.ts from levels/. Do not edit: change levels/, then run
// `deno task levels`.
import type { Level } from "./types.ts";

export const tutorial: readonly Level[] = [{
  id: 1,
  code:
    "int f(int x, int y) {\n  // numbers represent colors\n  int red = 2;\n  return x == 1 && y == 2 ? red : 0;\n}",
  solution: [
    "00000000",
    "00000000",
    "02000000",
    "00000000",
    "00000000",
    "00000000",
    "00000000",
    "00000000",
  ],
}, {
  id: 2,
  code: "int f(int x, int y) {\n  // tip: drag to paint\n  return x;\n}",
  solution: [
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
  ],
}, {
  id: 3,
  code: "int f(int x, int y) {\n  // integer division\n  return x / 2;\n}",
  solution: [
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
    "00112233",
  ],
}, {
  id: 4,
  code: "int f(int x, int y) {\n  return (x/2 + y/4) % 2;\n}",
  solution: [
    "00110011",
    "00110011",
    "00110011",
    "00110011",
    "11001100",
    "11001100",
    "11001100",
    "11001100",
  ],
}, {
  id: 5,
  code: "int f(int x, int y) {\n  // available: max, min, abs\n  return max(x, y);\n}",
  solution: [
    "01234567",
    "11234567",
    "22234567",
    "33334567",
    "44444567",
    "55555567",
    "66666667",
    "77777777",
  ],
}, {
  id: 6,
  code: "int f(int x, int y) {\n  // a comparison gives 1 or 0\n  return (x*2 < y) * 7;\n}",
  solution: [
    "00000000",
    "70000000",
    "70000000",
    "77000000",
    "77000000",
    "77700000",
    "77700000",
    "77770000",
  ],
}, {
  id: 7,
  code: "int f(int x, int y) {\n  int w[] = {1,2,3,4,4,3,2,1};\n  return x < w[y] ? 5 : 0;\n}",
  solution: [
    "50000000",
    "55000000",
    "55500000",
    "55550000",
    "55550000",
    "55500000",
    "55000000",
    "50000000",
  ],
}, {
  id: 8,
  code:
    "int f(int x, int y) {\n  // bitwise left shift\n  int b = 1 << x;\n  // hexadecimal bitmask\n  int mask = 0xB0; // 10110000\n  return b & mask ? 1 : 0;\n}",
  solution: [
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
    "00001101",
  ],
}];

export const daily: readonly Level[] = [{
  id: 1,
  code:
    "int f(int x, int y) {\n  int dx = 2*x - 7, dy = 2*y - 7;\n  return dx*dx + dy*dy < 40 ? 2 : 0;\n}",
  solution: [
    "00000000",
    "00222200",
    "02222220",
    "02222220",
    "02222220",
    "02222220",
    "00222200",
    "00000000",
  ],
}, {
  id: 2,
  code: "int f(int x, int y) {\n  return (x & y) == 0;\n}",
  solution: [
    "11111111",
    "10101010",
    "11001100",
    "10001000",
    "11110000",
    "10100000",
    "11000000",
    "10000000",
  ],
}, {
  id: 3,
  code: "int f(int x, int y) {\n  return x ^ y;\n}",
  solution: [
    "01234567",
    "10325476",
    "23016745",
    "32107654",
    "45670123",
    "54761032",
    "67452301",
    "76543210",
  ],
}, {
  id: 4,
  code: "int f(int x, int y) {\n  return (x ^ y) >> 1 & 1 ? 6 : 4;\n}",
  solution: [
    "44664466",
    "44664466",
    "66446644",
    "66446644",
    "44664466",
    "44664466",
    "66446644",
    "66446644",
  ],
}, {
  id: 5,
  code:
    "int f(int x, int y) {\n  int dx = abs(2*x - 7);\n  int dy = abs(2*y - 7);\n  return max(dx, dy) / 2;\n}",
  solution: [
    "33333333",
    "32222223",
    "32111123",
    "32100123",
    "32100123",
    "32111123",
    "32222223",
    "33333333",
  ],
}, {
  id: 6,
  code: "int f(int x, int y) {\n  int d = abs(x - 3) + abs(y - 4);\n  return 5 - min(d, 5);\n}",
  solution: [
    "00010000",
    "00121000",
    "01232100",
    "12343210",
    "23454321",
    "12343210",
    "01232100",
    "00121000",
  ],
}, {
  id: 7,
  code:
    "int f(int x, int y) {\n  // Bits set in x * y, and a twist.\n  int v = x * y;\n  int bits = 0;\n  while (v > 0) {\n    bits += v & 1;\n    v /= 2;\n  }\n  if (bits >= 4)\n    return 7;\n  return bits + (x + y) % 2 * 4;\n}",
  solution: [
    "04040404",
    "41525263",
    "05161627",
    "42626763",
    "05161627",
    "42676373",
    "06262727",
    "43737373",
  ],
}, {
  id: 8,
  code: "int f(int x, int y) {\n  return 1 << x & 0x5A ? 1 : 0;\n}",
  solution: [
    "01011010",
    "01011010",
    "01011010",
    "01011010",
    "01011010",
    "01011010",
    "01011010",
    "01011010",
  ],
}, {
  id: 9,
  code: "int f(int x, int y) {\n  int a[] = {0,2,3,4,5,6,7,0};\n  return a[y];\n}",
  solution: [
    "00000000",
    "22222222",
    "33333333",
    "44444444",
    "55555555",
    "66666666",
    "77777777",
    "00000000",
  ],
}, {
  id: 10,
  code:
    "int f(int x, int y) {\n  int c = 1 << x;\n  int a[] = {\n    c & 0x14 ? 3:0, c & 0x1E ? 5:0,\n    c & 0x35 ? 5:0, c & 0x1F ? 5:0,\n    c & 0x3C ? 5:0, c & 0x9E ? 5:0,\n    c & 0x7C ? 5:0, c & 0x14 ? 5:0,\n  };\n  return a[y];\n}",
  solution: [
    "00303000",
    "05555000",
    "50505500",
    "55555000",
    "00555500",
    "05555005",
    "00555550",
    "00505000",
  ],
}, {
  id: 11,
  code:
    "int f(int x, int y) {\n  int a[] = {\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7,\n    0,1,2,3,4,5,6,7};\n  return a[x + y*8];\n}",
  solution: [
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
    "01234567",
  ],
}];
