/** A cell value: a palette index. Every cell always holds one; there is no empty state. */
export type Color = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

/** 64 cells, row by row: the cell at (x, y) is `grid[y * 8 + x]`. */
export type Grid = readonly Color[];

export const SIZE = 8;
export const CELLS = SIZE * SIZE;

export function isColor(value: unknown): value is Color {
  return Number.isInteger(value) && (value as number) >= 0 && (value as number) <= 7;
}

export function cellIndex(x: number, y: number): number {
  return y * SIZE + x;
}

/** The starting grid: every cell 0 (black). */
export function blankGrid(): Grid {
  return Array<Color>(CELLS).fill(0);
}

/** A grid as 64 digits, the form kept in storage. */
export function gridToString(grid: Grid): string {
  return grid.join("");
}

/** Reads 64 digits in [0, 7]; anything else gives undefined. */
export function gridFromString(text: string): Grid | undefined {
  if (!/^[0-7]{64}$/.test(text)) return undefined;
  return [...text].map((digit) => Number(digit) as Color);
}

/** Reads a level's solution: 8 rows of 8 digits, as generated by tools/levels.ts. */
export function gridFromRows(rows: readonly string[]): Grid {
  const grid = rows.length === SIZE ? gridFromString(rows.join("")) : undefined;
  if (!grid) throw new Error(`Malformed solution: ${JSON.stringify(rows)}`);
  return grid;
}

/** Returns the same grid when nothing changes, including for an index outside the grid. */
export function setCell(grid: Grid, index: number, color: Color): Grid {
  if (grid[index] === undefined || grid[index] === color) return grid;
  return grid.map((cell, i) => (i === index ? color : cell));
}

export function sameGrid(a: Grid, b: Grid): boolean {
  return a.length === b.length && a.every((cell, i) => cell === b[i]);
}

/** How many cells differ from the solution: the only feedback a wrong submit gives. */
export function wrongCount(grid: Grid, solution: Grid): number {
  return grid.reduce<number>((count, cell, i) => count + (cell === solution[i] ? 0 : 1), 0);
}
