/**
 * What the level generator writes and prints: src/levels/generated.ts, a terminal preview of each
 * new or changed level, and the daily schedule.
 */

import { type CalendarDate, daysBetween, formatIsoDate } from "../src/core/date.ts";
import { puzzleDate } from "../src/core/schedule.ts";
import type { Level } from "../src/levels/types.ts";
import { PALETTE } from "../src/ui/palette.ts";
import { pathToFileURL } from "node:url";

export interface LevelSet {
  readonly tutorial: readonly Level[];
  readonly daily: readonly Level[];
}

/** The 64 harness values as 8 rows of 8 digits, the form stored in generated.ts. */
export function toRows(values: readonly number[]): string[] {
  return Array.from({ length: 8 }, (_, y) => values.slice(y * 8, y * 8 + 8).join(""));
}

/** generated.ts before `deno fmt`, which then lays out one solution row per line. */
export function renderGenerated(levels: LevelSet): string {
  const literal = (level: Level) =>
    `{ id: ${level.id}, code: ${JSON.stringify(level.code)}, solution: [${
      level.solution.map((row) => JSON.stringify(row)).join(", ")
    }] }`;
  const list = (name: string, items: readonly Level[]) =>
    `export const ${name}: readonly Level[] = [${items.map(literal).join(", ")}];\n`;
  return [
    "// Generated by tools/levels.ts from levels/. Do not edit: change levels/, then run",
    "// `deno task levels`.",
    'import type { Level } from "./types.ts";',
    "",
    list("tutorial", levels.tutorial),
    list("daily", levels.daily),
  ].join("\n");
}

let reads = 0;

/**
 * The levels in an existing generated.ts, to tell new and changed levels apart. Missing or
 * malformed files read as no levels: `--check` then reports the file as out of date anyway.
 */
export async function readGenerated(path: string): Promise<LevelSet> {
  try {
    // A fresh query string per read, or Deno would return the module it loaded the first time.
    const module = await import(`${pathToFileURL(path).href}?read=${++reads}`);
    const { tutorial, daily } = module as Record<string, unknown>;
    if (isLevelList(tutorial) && isLevelList(daily)) return { tutorial, daily };
  } catch {
    // Handled below, like a file with an unexpected shape.
  }
  return { tutorial: [], daily: [] };
}

function isLevelList(value: unknown): value is Level[] {
  return Array.isArray(value) &&
    value.every((level) =>
      typeof level?.id === "number" && typeof level.code === "string" &&
      Array.isArray(level.solution) &&
      level.solution.every((row: unknown) => typeof row === "string")
    );
}

export function sameLevel(a: Level, b: Level): boolean {
  return a.code === b.code && a.solution.join() === b.solution.join();
}

/** Formats TypeScript exactly as `deno fmt` would, using the repo's config. */
export async function denoFmt(source: string, cwd: string): Promise<string> {
  const child = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "--ext=ts", "-"],
    cwd,
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  const writer = child.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { success, stdout, stderr } = await child.output();
  if (!success) throw new Error(`deno fmt failed:\n${new TextDecoder().decode(stderr)}`);
  return new TextDecoder().decode(stdout);
}

function background(hex: string): string {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
  return `\x1b[48;2;${r};${g};${b}m  \x1b[0m`;
}

/** The level's code next to its grid, in truecolor. */
export function preview(title: string, level: Level): string {
  const code = level.code.split("\n");
  const grid = level.solution.map((row) =>
    [...row].map((digit) => background(PALETTE[Number(digit)]?.hex ?? "#000000")).join("")
  );
  const lines = Array.from(
    { length: Math.max(code.length, grid.length) },
    (_, i) => `  ${(code[i] ?? "").padEnd(38)}${grid[i] ?? ""}`,
  );
  return [title, ...lines].join("\n");
}

export interface Schedule {
  readonly line: string;
  readonly daysLeft: number;
}

/** "Daily puzzles scheduled until YYYY-MM-DD (N days left)", counted from `today`. */
export function schedule(launch: CalendarDate, dailyCount: number, today: CalendarDate): Schedule {
  if (dailyCount === 0) return { line: "No daily puzzles yet", daysLeft: -1 };
  const last = puzzleDate(launch, dailyCount);
  const daysLeft = daysBetween(today, last);
  const line = daysLeft >= 0
    ? `Daily puzzles scheduled until ${formatIsoDate(last)} (${daysLeft} days left)`
    : `Daily puzzles ran out on ${formatIsoDate(last)} (${-daysLeft} days ago)`;
  return { line, daysLeft };
}
