/**
 * What the level generator writes and prints: src/levels/generated.ts, and a terminal preview of
 * each new or changed level.
 */

import type { Levels } from "../src/core/schedule.ts";
import type { Epoch, Level, Puzzle, SpecialLevel } from "../src/levels/types.ts";
import { PALETTE } from "../src/ui/palette.ts";
import { pathToFileURL } from "node:url";

/** Everything generated.ts holds: the tutorial, then the daily schedule. */
export interface LevelSet extends Levels {
  readonly tutorial: readonly Level[];
}

export const NO_LEVELS: LevelSet = { tutorial: [], daily: [], special: [], epochs: [] };

/** The 64 harness values as 8 rows of 8 digits, the form stored in generated.ts. */
export function toRows(values: readonly number[]): string[] {
  return Array.from({ length: 8 }, (_, y) => values.slice(y * 8, y * 8 + 8).join(""));
}

/** generated.ts before `deno fmt`, which then lays out one solution row per line. */
export function renderGenerated(levels: LevelSet): string {
  const puzzle = (level: Puzzle) =>
    `code: ${JSON.stringify(level.code)}, solution: [${
      level.solution.map((row) => JSON.stringify(row)).join(", ")
    }]`;
  const level = (l: Level) => `{ id: ${l.id}, ${puzzle(l)} }`;
  const special = (l: SpecialLevel) =>
    `{ month: ${l.month}, day: ${l.day}, name: ${JSON.stringify(l.name)}, ${puzzle(l)} }`;
  const epoch = (e: Epoch) => `{ from: ${e.from}, size: ${e.size}, start: ${e.start} }`;
  const list = <T>(name: string, type: string, items: readonly T[], literal: (item: T) => string) =>
    `export const ${name}: readonly ${type}[] = [${items.map(literal).join(", ")}];\n`;
  return [
    "// Generated by tools/levels.ts from levels/. Do not edit: change levels/, then run",
    "// `deno task levels`.",
    'import type { Epoch, Level, SpecialLevel } from "./types.ts";',
    "",
    list("tutorial", "Level", levels.tutorial, level),
    "/** The daily pool, in order: it loops forever. */",
    list("daily", "Level", levels.daily, level),
    "/** Shown every year on their date, in place of the pool's level. */",
    list("special", "SpecialLevel", levels.special, special),
    "/** How the loop runs over the pool: a new epoch each time the pool changed size after launch. */",
    list("epochs", "Epoch", levels.epochs, epoch),
  ].join("\n");
}

let reads = 0;

/**
 * The levels in an existing generated.ts, to tell new and changed levels apart and to keep past
 * days stable; undefined when the file is missing or can't be read (a merge conflict, say). A file
 * from before specials and epochs reads with none.
 */
export async function readGenerated(path: string): Promise<LevelSet | undefined> {
  try {
    // A fresh query string per read, or Deno would return the module it loaded the first time.
    const module = await import(`${pathToFileURL(path).href}?read=${++reads}`);
    const { tutorial, daily, special = [], epochs = [] } = module as Record<string, unknown>;
    if (
      isList(tutorial, isLevel) && isList(daily, isLevel) && isList(special, isSpecial) &&
      isList(epochs, isEpoch)
    ) {
      return { tutorial, daily, special, epochs };
    }
  } catch {
    // Handled below, like a file with an unexpected shape.
  }
  return undefined;
}

function isList<T>(value: unknown, isItem: (item: unknown) => item is T): value is T[] {
  return Array.isArray(value) && value.every(isItem);
}

function isPuzzle(value: unknown): value is Puzzle {
  const v = value as Record<string, unknown> | null;
  return typeof v?.code === "string" && Array.isArray(v.solution) &&
    v.solution.every((row: unknown) => typeof row === "string");
}

function isLevel(value: unknown): value is Level {
  return isPuzzle(value) && typeof (value as Level).id === "number";
}

function isSpecial(value: unknown): value is SpecialLevel {
  const v = value as SpecialLevel;
  return isPuzzle(value) && typeof v.month === "number" && typeof v.day === "number" &&
    typeof v.name === "string";
}

function isEpoch(value: unknown): value is Epoch {
  const v = value as Epoch | null;
  return typeof v?.from === "number" && typeof v.size === "number" && typeof v.start === "number";
}

export function sameLevel(a: Puzzle, b: Puzzle): boolean {
  return a.code === b.code && a.solution.join() === b.solution.join();
}

/** Formats TypeScript exactly as `deno fmt` would, using the repo's config. */
export async function denoFmt(source: string, cwd: string): Promise<string> {
  const child = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "--ext=ts", "-"],
    cwd,
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  const writer = child.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { success, stdout, stderr } = await child.output();
  if (!success) throw new Error(`deno fmt failed:\n${new TextDecoder().decode(stderr)}`);
  return new TextDecoder().decode(stdout);
}

function background(hex: string): string {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
  return `\x1b[48;2;${r};${g};${b}m  \x1b[0m`;
}

/** The level's code next to its grid, in truecolor. */
export function preview(title: string, level: Puzzle): string {
  const code = level.code.split("\n");
  const grid = level.solution.map((row) =>
    [...row].map((digit) => background(PALETTE[Number(digit)]?.hex ?? "#000000")).join("")
  );
  const lines = Array.from(
    { length: Math.max(code.length, grid.length) },
    (_, i) => `  ${(code[i] ?? "").padEnd(38)}${grid[i] ?? ""}`,
  );
  return [title, ...lines].join("\n");
}
